export const SITE = {
  name: "A. Jiménez Pool Service",
  phone: "305-417-0116",
  whatsapp: "13054170116",
  email: "info@ajimenezpoolservice.com",
  domain: "ajimenezpoolservice.com",
  location: "Miami, FL",
  certification: "SPO Certified",
  available: "24/7",
} as const;

export const COLORS = {
  navy: "#0a1628",
  royalBlue: "#1e56a0",
  cyan: "#36b5e0",
  lightBlue: "#7dd3fc",
  white: "#ffffff",
  black: "#111111",
  darkBg: "#030a1a",
} as const;

export const SERVICES = [
  {
    slug: "pool-cleaning",
    titleEn: "Pool Cleaning",
    titleEs: "Limpieza de Piscina",
    descEn: "Regular professional pool cleaning to keep your water crystal clear and safe for swimming.",
    descEs: "Limpieza profesional regular para mantener su agua cristalina y segura para nadar.",
    icon: "sparkles",
  },
  {
    slug: "pool-maintenance",
    titleEn: "Pool Maintenance",
    titleEs: "Mantenimiento de Piscina",
    descEn: "Weekly and monthly preventive maintenance to extend the life of your pool.",
    descEs: "Mantenimiento preventivo semanal y mensual para alargar la vida de su piscina.",
    icon: "wrench",
  },
  {
    slug: "chemical-balancing",
    titleEn: "Chemical Balancing",
    titleEs: "Balanceo Químico",
    descEn: "Expert water chemistry management for perfectly balanced, safe pool water.",
    descEs: "Gestión experta de la química del agua para un equilibrio perfecto y seguro.",
    icon: "beaker",
  },
  {
    slug: "filter-cleaning",
    titleEn: "Filter Cleaning",
    titleEs: "Limpieza de Filtros",
    descEn: "Thorough filter cleaning and maintenance for optimal water circulation.",
    descEs: "Limpieza y mantenimiento exhaustivo de filtros para una circulación óptima.",
    icon: "filter",
  },
  {
    slug: "pool-resurfacing",
    titleEn: "Pool Resurfacing",
    titleEs: "Repavimentación de Piscina",
    descEn: "Complete pool resurfacing to restore your pool's beauty and structural integrity.",
    descEs: "Repavimentación completa para restaurar la belleza e integridad de su piscina.",
    icon: "paintBucket",
  },
  {
    slug: "tile-grout-cleaning",
    titleEn: "Tile & Grout Cleaning",
    titleEs: "Limpieza de Azulejos y Juntas",
    descEn: "Deep cleaning of pool tiles and grout lines for a pristine finish.",
    descEs: "Limpieza profunda de azulejos y juntas para un acabado impecable.",
    icon: "grid",
  },
  {
    slug: "salt-system-installation",
    titleEn: "Salt System Installation",
    titleEs: "Instalación Sistema de Sal",
    descEn: "Professional salt chlorination system installation for gentler, easier pool care.",
    descEs: "Instalación profesional de cloración salina para un cuidado más suave y fácil.",
    icon: "zap",
  },
  {
    slug: "green-pool-recovery",
    titleEn: "Green Pool Recovery",
    titleEs: "Recuperación de Piscina Verde",
    descEn: "Rapid green-to-clean service. We transform algae-infested pools back to crystal clear.",
    descEs: "Servicio rápido de verde a limpio. Transformamos piscinas con algas a cristalinas.",
    icon: "leaf",
  },
  {
    slug: "pool-acid-wash",
    titleEn: "Pool Acid Wash",
    titleEs: "Lavado Ácido",
    descEn: "Professional acid washing to remove stubborn stains and restore your pool's surface.",
    descEs: "Lavado ácido profesional para eliminar manchas difíciles y restaurar la superficie.",
    icon: "droplets",
  },
  {
    slug: "pool-drain-refill",
    titleEn: "Pool Drain & Refill",
    titleEs: "Vaciado y Rellenado",
    descEn: "Complete pool draining and refilling with proper chemical balancing.",
    descEs: "Vaciado y rellenado completo con balanceo químico adecuado.",
    icon: "arrowDownUp",
  },
  {
    slug: "deck-pressure-washing",
    titleEn: "Deck Pressure Washing",
    titleEs: "Lavado a Presión del Deck",
    descEn: "High-pressure deck cleaning to remove dirt, mold, and restore your pool area.",
    descEs: "Lavado a presión del deck para eliminar suciedad, moho y restaurar el área de la piscina.",
    icon: "waves",
  },
  {
    slug: "health-department-compliance",
    titleEn: "Health Department Compliance",
    titleEs: "Cumplimiento Dept. de Salud",
    descEn: "Ensure your pool meets all Florida Health Department regulations and standards.",
    descEs: "Aseguramos que su piscina cumple con todas las regulaciones del Dept. de Salud de Florida.",
    icon: "shieldCheck",
  },
] as const;

export const NAV_LINKS = [
  { href: "/services", labelEn: "Services", labelEs: "Servicios" },
  { href: "/about", labelEn: "About", labelEs: "Nosotros" },
  { href: "/gallery", labelEn: "Gallery", labelEs: "Galería" },
  { href: "/calculator", labelEn: "Calculator", labelEs: "Calculadora" },
  { href: "/contact", labelEn: "Contact", labelEs: "Contacto" },
] as const;
